### PR TITLE
Add DOMPurify for safe HTML rendering in FeaturedAnnouncement component

### PR DESCRIPTION
**Pull request by fcendesu**
This pull request includes several changes to enhance the handling and display of announcements in the application. The key updates involve the introduction of the `DOMPurify` library for sanitizing HTML content and the modification of announcement properties to support optional values and default messages.

### Enhancements to announcement handling:

* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R20): Added `@types/dompurify` to `devDependencies` to support the new sanitization functionality.

* `src/components/FeaturedAnnouncement.tsx`: 
  * Imported `DOMPurify` for sanitizing HTML content.
  * Updated `FeaturedAnnouncementProps` to make `announcementTR` and `announcementEN` optional and provide default values.
  * Added logic to use `DOMPurify.sanitize` for safely rendering HTML content in announcements.
  * Included fallback messages for cases where announcements are not available in the selected language.

### Updates to announcement content:

* [`src/app/page.tsx`](diffhunk://#diff-73d7a23e5015801b9bcc9db601d6ec9594d3eb34e5bb23154e0ae4b0c30f1a3bL118-R119): Changed the announcement strings to include HTML tags for better formatting.

This closes issue #6

### CODE REVIEW

**Comment by atasoya** [comment]
It seems that there is a problem with your `sanitize` implementation. Also, somehow `package.json` is missing `dompurify` as a dependency.

I managed to get it to work on my local setup after adding `dompurify` as a dependency using (`npm install dompurify`), but I was still getting type errors about `DOMPurify.sanitize`.

Also, can you please change the default `show` setting from `true` to `false`?

**Comment by fcendesu** [comment]
This pull request includes changes to enhance the `FeaturedAnnouncement` component by sanitizing HTML content, updating dependencies, and modifying the announcement display logic. The most important changes are listed below:

### Dependency Updates:
* Added `dompurify` and `@types/dompurify` to the dependencies in `package.json` to ensure safe HTML rendering.

### Component Enhancements:
* [`src/components/FeaturedAnnouncement.tsx`](diffhunk://#diff-fbec8b6182042f80afc66ca10857a7e63cd661039fc0c383a20567682bb17b37R2-R40): Imported `DOMPurify` and used it to sanitize announcement content before rendering it with `dangerouslySetInnerHTML`. Updated the component to provide default values for props and added a fallback message if the announcement is not available.
* [`src/app/page.tsx`](diffhunk://#diff-73d7a23e5015801b9bcc9db601d6ec9594d3eb34e5bb23154e0ae4b0c30f1a3bL115-R119): Modified the `FeaturedAnnouncement` component to use sanitized HTML content for the announcements and set the `show` prop to `false`.

**Review by atasoya — COMMENTED** [review]
Everything looks fine, let's check the Vercel deployment.

**Review by atasoya — CHANGES_REQUESTED** [review]
There's still an issue with your DOMPurify.sanitize() implementation. After some research, I found [this solution](https://sentry.io/answers/using-dangerouslysetinnerhtml-in-next-js/#server-side). 

Also, for better flexibility it would be better to return the entire section from the database.

**Pull request closed without merging**
